//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r2.DataBaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        public commande()
        {
            this.menu = new HashSet<menu>();
            this.produit = new HashSet<produit>();
        }
    
        public int commandeID { get; set; }
        public decimal prixtotal { get; set; }
        public Nullable<decimal> fraisdelivraison { get; set; }
        public Nullable<double> reduction { get; set; }
        public System.DateTime datecommande { get; set; }
        public string etatcommande { get; set; }
        public string clientID { get; set; }
        public int restaurantID { get; set; }
    
        public virtual client client { get; set; }
        public virtual restaurant restaurant { get; set; }
        public virtual ICollection<menu> menu { get; set; }
        public virtual ICollection<produit> produit { get; set; }
    }
}
