//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASLRD_r2.DataBaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public menu()
        {
            this.commande = new HashSet<commande>();
            this.commentaire = new HashSet<commentaire>();
            this.produit = new HashSet<produit>();
        }
    
        public int menuID { get; set; }
        public string nom { get; set; }
        public decimal prixmenu { get; set; }
        public string description { get; set; }
        public Nullable<System.TimeSpan> delais { get; set; }
        public Nullable<double> reduction { get; set; }
        public int restaurantID { get; set; }
    
        public virtual restaurant restaurant { get; set; }
        public virtual ICollection<commande> commande { get; set; }
        public virtual ICollection<commentaire> commentaire { get; set; }
        public virtual ICollection<produit> produit { get; set; }
    }
}
